// <auto-generated />
using System;
using Garimpo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Garimpo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GarimpoDbContext))]
    [Migration("20260606011510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Garimpo.Domain.Entities.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CentroidAltitudeKm")
                        .HasColumnType("double precision");

                    b.Property<double>("CentroidInclinationDegrees")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Density")
                        .HasColumnType("double precision");

                    b.Property<int>("Label")
                        .HasColumnType("integer");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("clusters", (string)null);
                });

            modelBuilder.Entity("Garimpo.Domain.Entities.Debris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AltitudeKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<double>("Eccentricity")
                        .HasColumnType("double precision");

                    b.Property<double>("InclinationDegrees")
                        .HasColumnType("double precision");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Line2")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double>("MeanMotionRevsPerDay")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("NoradId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AltitudeKm");

                    b.HasIndex("ClusterId");

                    b.HasIndex("NoradId")
                        .IsUnique();

                    b.ToTable("debris", (string)null);
                });

            modelBuilder.Entity("Garimpo.Domain.Entities.Debris", b =>
                {
                    b.HasOne("Garimpo.Domain.Entities.Cluster", "Cluster")
                        .WithMany("Members")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Garimpo.Domain.Entities.Cluster", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
